services:
  watchpot:
    build: .
    image: watchpot:latest
    restart: on-failure:10
    read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT}:8080"
    volumes:
      - ./config.yaml:/config.yaml:ro
    environment:
      - WATCHPOT_CONFIG=/config.yaml
      - REDIS_PASSWORD=${REDIS_PASSWORD}
